// Job options for Meridian/Boise, Idaho + Idaho-friendly remote ($30+/hr target).
// Pay figures are approximate mid-2026 market rates and vary by experience.
// Sourced from a multi-agent research sweep of USAJOBS, governmentjobs.com,
// employer career sites, Indeed/ZipRecruiter/LinkedIn, and vetted remote platforms.
window.JOBS_UPDATED = 'June 2026';

const JOBS = [
  // ───────────────────────────── GOVERNMENT ─────────────────────────────
  {
    category: 'Government',
    title: 'Federal: SSA/IRS Contact or Claims Representative',
    pay: '$25–$37/hr (GS-7 to GS-9, Boise locality)',
    format: 'onsite',
    requirements: "Bachelor's OR ~1 yr specialized experience. Customer-service/records aptitude. US citizenship + background check. GS-9 clears $30/hr.",
    notes: 'USAJOBS is the ONLY legit place to apply for federal jobs. Filter Location=Boise, Grade=GS-7/9 and set a Saved Search alert.',
    whereLabel: 'USAJOBS',
    url: 'https://www.usajobs.gov/Search?l=Idaho',
  },
  {
    category: 'Government',
    title: 'Federal: VA Boise Medical Support Assistant / Program Support',
    pay: '$28–$38/hr (GS-7/8 Advanced MSA & Program Support)',
    format: 'onsite',
    requirements: 'Entry-friendly. GS-5 needs ~1 yr experience or 2 yrs college; the $30+ tier is Advanced/Lead MSA, program support, and health tech. US citizenship preferred.',
    notes: 'VA is the largest federal employer in Boise with frequent openings. Apply through USAJOBS even when found on va.gov.',
    whereLabel: 'USAJOBS (VA)',
    url: 'https://www.usajobs.gov/Search/Results?l=Boise,+Idaho&d=VA',
  },
  {
    category: 'Government',
    title: 'Federal: BLM / Forest Service Technician & Program Support',
    pay: '$28–$40/hr (GS-7/GS-9 tier)',
    format: 'onsite',
    requirements: 'Degree or seasons of experience push you to GS-7+. Generalist admin/program-support and resource-technician roles available. US citizenship.',
    notes: 'Boise is a federal land-management hub (NIFC fire center is here). Permanent GS-7+ admin/dispatch roles clear $30/hr.',
    whereLabel: 'USAJOBS',
    url: 'https://www.usajobs.gov/',
  },
  {
    category: 'Government',
    title: 'State of Idaho: HR Specialist / Financial Specialist / Buyer / Business Analyst',
    pay: '$30–$36/hr ($62k–$75k/yr)',
    format: 'hybrid',
    requirements: 'Entry-to-mid generalist. Associate/bachelor or equivalent experience. Merit-system application, sometimes an online exam.',
    notes: 'Includes PERSI pension (one of the best state retirement systems). ~125 state jobs open in Boise at a time. All posted on governmentjobs.com.',
    whereLabel: 'Idaho State Careers',
    url: 'https://www.governmentjobs.com/careers/idaho',
  },
  {
    category: 'Government',
    title: 'State of Idaho: Compliance Officer / Program Specialist / IT Support',
    pay: '$30–$40/hr',
    format: 'hybrid',
    requirements: 'Mid-level generalist; good for career-changers. Compliance/program roles need a bachelor or relevant experience but are not narrowly technical.',
    notes: 'Aim for Specialist/Officer/Analyst-level titles — entry "Records Specialist" clerical roles start ~$17–$20/hr, below target.',
    whereLabel: 'Idaho State Careers',
    url: 'https://www.governmentjobs.com/careers/idaho',
  },
  {
    category: 'Government',
    title: 'City of Meridian: Senior Admin / Permit Tech / Utility Operator / Code Enforcement',
    pay: '$30–$40/hr (senior/technician tier)',
    format: 'onsite',
    requirements: 'Entry-to-mid generalist. Senior admin, planning/permit technician, utility operator (cert or trainee track), code enforcement. Some need a cert or 1–2 yrs experience.',
    notes: 'Your closest local government employer (Meridian, 83642). Smaller posting volume (~11 open) — target senior/technician titles, not entry clerk roles.',
    whereLabel: 'City of Meridian Jobs',
    url: 'https://meridiancity.wd12.myworkdayjobs.com/meridian_city',
  },
  {
    category: 'Government',
    title: 'City of Boise: Wastewater Operator / Senior CSR / Trades / Admin Specialist',
    pay: '$30–$40/hr (with cert)',
    format: 'onsite',
    requirements: 'Generalist-friendly. Wastewater Operator-in-training path, senior customer service rep, maintenance/trades, admin specialists. Many are trainable.',
    notes: 'Strong benefits: real pension, near-free healthcare, 401k match, tuition reimbursement. Wastewater Operator is a reliable $30+ on-ramp.',
    whereLabel: 'City of Boise Careers',
    url: 'https://www.governmentjobs.com/careers/boiseid',
  },
  {
    category: 'Government',
    title: 'Ada County: 911 Dispatcher / Detention Deputy / Appraiser / Accounting Specialist',
    pay: '$30+/hr after training/certification',
    format: 'onsite',
    requirements: 'Generalist routes: accounting/admin specialist, elections, appraiser trainee, 911 dispatcher (paid training), detention deputy (academy). Structured pay ladders.',
    notes: '2,100+ employees, 20 departments. Public-safety support roles have pay ladders that clear $30/hr after certification.',
    whereLabel: 'Ada County Careers',
    url: 'https://www.governmentjobs.com/careers/adacounty',
  },
  {
    category: 'Government',
    title: 'School Districts (West Ada / Boise): Teacher, IT, Skilled Support',
    pay: 'Teachers ~$48k–$70k+ (≈$30+/hr); IT & skilled-trades supervisors $30+/hr',
    format: 'onsite',
    requirements: 'Teaching cert + bachelor for classroom roles. Non-cert routes to $30+: IT support, skilled trades, nutrition/maintenance supervisors. (Aide/para roles start $16–$22/hr.)',
    notes: 'West Ada is the Meridian district — your local one. Good benefits and schedule. Target certified or skilled-supervisor titles to clear $30/hr.',
    whereLabel: 'West Ada Jobs',
    url: 'https://www.westada.org/Page/Careers',
  },

  // ───────────────────────────── OFFICE / ADMIN ─────────────────────────────
  {
    category: 'Office / Admin',
    title: 'Project Coordinator',
    pay: '~$27–$42/hr; avg ~$69.5k/yr — reliably hits $30+',
    format: 'hybrid',
    requirements: '2–5 yrs coordinating projects, scheduling, budget/document tracking; MS Project / Smartsheet / Asana. CAPM/PMP helps. Construction, engineering & tech reach the top end.',
    notes: 'One of the strongest $30+ office picks. Employers hiring: ACCO Engineered Systems, Lennar, State of Idaho, Lumin8.',
    whereLabel: 'ZipRecruiter',
    url: 'https://www.ziprecruiter.com/Jobs/Project-Coordinator/-in-Boise,ID',
  },
  {
    category: 'Office / Admin',
    title: 'Operations Coordinator / Administrator',
    pay: '~$26–$40/hr — can hit $30 at larger employers',
    format: 'hybrid',
    requirements: '2–5 yrs ops/admin support, process & vendor management, data + reporting, cross-team coordination. Pays best at scaled employers (Micron, Clearwater Analytics).',
    notes: 'Clearwater Analytics lists Recruiting/Legal/Product Ops Coordinator roles; Micron lists ops administrator + customer-success ops roles.',
    whereLabel: 'Indeed',
    url: 'https://www.indeed.com/q-operations-administrator-l-boise,-id-jobs.html',
  },
  {
    category: 'Office / Admin',
    title: 'Customer Success Manager (Idaho-friendly remote)',
    pay: 'US remote avg ~$83k/yr; manager level easily $30+/hr',
    format: 'remote',
    requirements: '2–4+ yrs customer-facing / account management / SaaS support. Strong communication + CRM (Salesforce/HubSpot). Entry "CS Specialist" is the on-ramp; CSM clears $30/hr.',
    notes: 'Best path to $30+ while staying remote in Idaho. Target NATIONAL remote roles (Idaho in-state CS pay ranks low). Imagine Learning hires remote CSMs.',
    whereLabel: 'Indeed (remote)',
    url: 'https://www.indeed.com/q-customer-success-manager-remote-jobs.html',
  },
  {
    category: 'Office / Admin',
    title: 'HR Coordinator → HR Generalist',
    pay: '~$30/hr at coordinator level; Generalist clears it reliably',
    format: 'hybrid',
    requirements: '2–4 yrs HR/recruiting support, HRIS (Workday/ADP), onboarding, benefits, I-9/compliance. Step up to HR Generalist or earn PHR/SHRM-CP to exceed $30/hr.',
    notes: 'Pure "Coordinator" sits right around the $30 line; "Generalist" / "HR Business Partner" titles clear it more dependably.',
    whereLabel: 'LinkedIn',
    url: 'https://www.linkedin.com/jobs/search/?keywords=hr%20coordinator&location=Boise%2C%20Idaho',
  },
  {
    category: 'Office / Admin',
    title: 'Executive Assistant / Office Manager / Bookkeeper (via staffing)',
    pay: '$25–$40/hr placements',
    format: 'hybrid',
    requirements: 'Robert Half places EAs, office managers, bookkeepers & finance pros into contract, contract-to-hire, and direct-hire roles. Good for breaking $30 without a senior title.',
    notes: 'Robert Half is the dominant admin/finance staffing firm in Boise — often the fastest route to $30+. Also try Express Employment, Aerotek/Actalent.',
    whereLabel: 'Robert Half Boise',
    url: 'https://www.roberthalf.com/us/en/jobs/boise/all',
  },
  {
    category: 'Office / Admin',
    title: 'Apply direct to major Boise/Meridian employers',
    pay: 'Varies — large employers most reliably post $30+ admin/ops roles with benefits',
    format: 'hybrid',
    requirements: 'Apply on company career sites (often pays more + better benefits than staffing). Tailor your resume to each posting; big employers screen via ATS keywords.',
    notes: 'Top employers: Micron (massive AI-driven expansion = 17,000+ new Idaho jobs), Albertsons HQ, St. Luke’s (largest private employer), Clearwater Analytics, HP, J.R. Simplot, Idaho Power.',
    whereLabel: 'Micron Careers',
    url: 'https://careers.micron.com',
  },

  // ─────────────────────── TECH / VIRTUAL ASSISTANT (REMOTE) ───────────────────────
  {
    category: 'Tech / VA (Remote)',
    title: 'AI Data Labeling / Model Training — DataAnnotation',
    pay: '$20–$40/hr; coding $25–$45/hr; expert work up to $55+/hr',
    format: 'remote',
    requirements: 'Strong writing/reasoning; coding or domain expertise boosts pay & access. Unpaid screening assessment to qualify. No degree strictly required.',
    notes: 'LEGIT (operated by Surge AI). Caveat: task availability is feast-or-famine, so best as supplemental income, not a sole job. 1099 contractor.',
    whereLabel: 'DataAnnotation',
    url: 'https://www.dataannotation.tech',
  },
  {
    category: 'Tech / VA (Remote)',
    title: 'AI Trainer / Expert — Mercor',
    pay: 'Avg ~$31/hr; specialized/expert tracks $40–$100+/hr',
    format: 'remote',
    requirements: 'Resume + AI video interview screening. Geared toward credentialed experts (degree / professional experience). Higher bar than DataAnnotation or Outlier.',
    notes: 'LEGIT — vets and matches experts to AI labs. Best if you have a real professional specialty. Apply only via mercor.com.',
    whereLabel: 'Mercor',
    url: 'https://mercor.com',
  },
  {
    category: 'Tech / VA (Remote)',
    title: 'Virtual Executive Assistant — Boldly (W2 + benefits)',
    pay: '$27–$31/hr, W2 employee with PTO, benefits, tech stipend',
    format: 'remote',
    requirements: 'High bar: ~7–10+ yrs executive/admin assistant experience. Rigorous, selective vetting. US-based — Idaho eligible.',
    notes: 'LEGIT and one of the few W2 (not 1099) VA options — the best-paying VA agency for experienced EAs. Apply directly; never pay to apply.',
    whereLabel: 'Boldly Careers',
    url: 'https://boldly.com/careers',
  },
  {
    category: 'Tech / VA (Remote)',
    title: 'Remote Technical Support / Help Desk / IT Support',
    pay: '~$23/hr entry; CompTIA A+ roles avg ~$31/hr; dual-cert ~$34/hr',
    format: 'remote',
    requirements: 'Troubleshoot hardware/software/networks by phone/chat/email. Certs raise pay sharply — Google IT Support Certificate and/or CompTIA A+.',
    notes: 'LEGIT category. To reliably clear $30/hr, get certified. Dell, HP, BCBS hire A+ holders. Google cert: grow.google/certificates/it-support',
    whereLabel: 'Indeed ($30 remote)',
    url: 'https://www.indeed.com/q-tech-support-$30-l-remote-jobs.html',
  },
  {
    category: 'Tech / VA (Remote)',
    title: 'Online Tutoring (set-your-own-rate platforms)',
    pay: '$15–$80+/hr; Wyzant tutors set $30–$100+ (keep ~75%)',
    format: 'remote',
    requirements: 'Subject mastery. Wyzant/Preply need no formal credential; Tutor.com/Skooli require a degree or teaching cert. High-demand subjects (coding, math, test prep, science) pay most.',
    notes: 'Platforms are LEGIT, but tutoring on general job boards is scam-prone — stick to established platforms. Preply: Java ~$30, JavaScript ~$45/hr.',
    whereLabel: 'Wyzant',
    url: 'https://www.wyzant.com/tutor',
  },
  {
    category: 'Tech / VA (Remote)',
    title: 'Remote Chat / Email Customer Support (no-phone)',
    pay: '$25–$33/hr for the better roles',
    format: 'remote',
    requirements: 'Strong writing, fast typing, empathy, high-volume live chat/email. Often no degree; product/SaaS knowledge helps reach top pay.',
    notes: 'MIXED — real roles exist (Chatdesk, SaaS firms on WeWorkRemotely) but "$30/hr, no experience" chat ads are heavily scam-baited. Vet every employer.',
    whereLabel: 'We Work Remotely',
    url: 'https://weworkremotely.com/categories/remote-customer-support-jobs',
  },

  // ─────────────────────── OTHER / GENERALIST PATHS ───────────────────────
  {
    category: 'Other / Generalist',
    title: 'Outside Sales / Account Rep (base + uncapped commission)',
    pay: '$70k–$120k OTE (~$34–$58/hr equivalent)',
    format: 'hybrid',
    requirements: 'Low formal barrier — motivation, communication, reliable vehicle. Packaging, business services, medical device, home services all hire generalists and train.',
    notes: 'Best income ceiling here for a motivated generalist with no credential. Early ramp may dip below $30 — target roles with a guaranteed draw/base.',
    whereLabel: 'ZipRecruiter Sales',
    url: 'https://www.ziprecruiter.com/Jobs/Sales/-in-Boise,ID',
  },
  {
    category: 'Other / Generalist',
    title: 'Warehouse / Logistics Supervisor or Lead',
    pay: '$30.00–$33.68/hr (lead/supervisor tier; night & 2nd shift pay more)',
    format: 'onsite',
    requirements: 'Supervisory/leadership experience in a warehouse setting (hiring, training, coaching). Any team-lead history qualifies. Associate role is $18–$20/hr.',
    notes: 'Meridian/Boise have a large distribution presence (Amazon, retail DCs). Take an associate role and promote into lead within months if needed.',
    whereLabel: 'Indeed Warehouse',
    url: 'https://www.indeed.com/q-warehouse-jobs-l-boise,-id-jobs.html',
  },
  {
    category: 'Other / Generalist',
    title: 'Remote Medical Coder (CPC/CCA certified)',
    pay: 'Avg ~$30/hr ($25–$34); remote-from-Idaho',
    format: 'remote',
    requirements: 'Need CPC (AAPC) or CCA/CCS (AHIMA) cert — ~3–6 month self-paced course + exam. Then ICD-10/CPT/HCPCS + an EHR. Entry-level remote roles exist post-cert.',
    notes: 'A true work-from-home $30/hr path with a credential, not a degree. Pair cert study with a day job to bridge income.',
    whereLabel: 'AAPC Job Board',
    url: 'https://jobs.aapc.com/jobs/?city=Remote',
  },
  {
    category: 'Other / Generalist',
    title: 'Freelance Bookkeeper (remote, your own clients)',
    pay: '$20–$50/hr; $30+ achievable with a few clients + QuickBooks cert',
    format: 'remote',
    requirements: 'Low startup cost (computer + software). No degree. Get QuickBooks Online Accountant (free) + optional Certified Bookkeeper cert. Build clients via referrals/freelance platforms.',
    notes: 'Scalable side-business that becomes full-time. Start with Intuit/QuickBooks Live W-2 work to learn, then convert to higher-rate clients.',
    whereLabel: 'Intuit Bookkeeping',
    url: 'https://www.intuit.com/expert-careers/bookkeeping-jobs/',
  },
  {
    category: 'Other / Generalist',
    title: 'Skilled Trades Apprentice (Electrical / Plumbing / HVAC)',
    pay: 'Starts ~$17–$20/hr → ~$30/hr by year 3–4; journeyman median ~$30/hr (top >$50)',
    format: 'onsite',
    requirements: 'No degree. Get hired by a contractor + enroll in apprenticeship (CWI or IEC Idaho). "Earn while you learn" — paid from day one with structured raises.',
    notes: 'Not instant $30 — a 2–4 yr ramp — but durable, high-ceiling, recession-resistant. Best long-game pick; plumbing/electrical reach $30 fastest.',
    whereLabel: 'IEC Idaho',
    url: 'https://iecidaho.com/careers/',
  },
  {
    category: 'Other / Generalist',
    title: 'Local CDL-A Driver / High-end Delivery Driver',
    pay: '$29–$31.50/hr; some local delivery roles explicitly $30/hr + incentives',
    format: 'onsite',
    requirements: 'Some $30 delivery roles need only a regular license. CDL-A: company-paid training available (Sysco, Waste Connections) removes the upfront cost. Local hauls keep you home nightly.',
    notes: 'Meridian-based hauls available (Ruan). Hiring: Sysco, PepsiCo, Waste Connections, AAA Cooper.',
    whereLabel: 'ZipRecruiter CDL',
    url: 'https://www.ziprecruiter.com/Jobs/Cdl-Truck-Driver/-in-Boise,ID',
  },
  {
    category: 'Other / Generalist',
    title: 'Travel / Per-Diem CNA (specialty & psych shifts)',
    pay: '$30–$34/hr on specialty/per-diem shifts (staff CNA averages only ~$17–$19/hr)',
    format: 'onsite',
    requirements: 'Idaho CNA cert (4–8 week course at CWI, then state exam). Low barrier. To reach $30+: pick up per-diem/specialty shifts via gig-nursing apps; target psych/behavioral units.',
    notes: 'Fastest healthcare entry point and a stepping stone to LPN/RN or phlebotomy. The $30+ requires deliberately chasing per-diem/specialty, not default staff roles.',
    whereLabel: 'Nursa (per-diem)',
    url: 'https://nursa.com',
  },

  // ─────────────────────── REFERENCE: AVOID SCAMS ───────────────────────
  {
    category: 'Avoid Scams',
    title: '⚠️ How to spot a job scam (read this first)',
    pay: 'Remote-job-scam losses hit $521M in 2026 (FTC)',
    format: 'remote',
    requirements: 'RED FLAGS: pay for training/equipment/background checks; payment via crypto/gift cards/wire/Zelle; "deposit this check and forward money"; reshipping packages; hired in hours with no real interview; vague generic listings.',
    notes: 'VERIFY every employer: check BBB, Glassdoor, and search "company name + scam". Legit employers NEVER ask you to pay or to move money. Apply via official company sites only.',
    whereLabel: 'FTC Job Scams',
    url: 'https://consumer.ftc.gov/articles/job-scams',
  },
];
