// Job options for Meridian/Boise, Idaho + Idaho-friendly remote ($30+/hr target).
//
// HONESTY NOTE: This environment's network policy blocks me from opening job
// sites, so I CANNOT click-through-verify that any individual posting is open
// today. Instead, every link below points to an OFFICIAL, SELF-UPDATING search
// page (or an always-open application) — open it and you see whatever is live
// right now. The `verify` field states exactly how reliable each link is.
//
// Pay figures are approximate mid-2026 MARKET ESTIMATES and vary by experience —
// confirm the real number on the posting itself.
window.JOBS_UPDATED = 'June 27, 2026';

// verify levels:
//   official   = employer's own portal; shows only currently-open reqs (most reliable)
//   signup     = always-open application; apply anytime, not a dated posting
//   aggregator = third-party board (Indeed/ZipRecruiter/LinkedIn); real but MIXED currency — check each posting's date
const JOBS = [
  // ───────────────────────────── GOVERNMENT ─────────────────────────────
  {
    category: 'Government',
    title: 'Federal jobs in Boise (SSA / IRS / VA / BLM / Forest Service)',
    pay: '$28–$40/hr at GS-7/GS-9 (Boise locality); GS-9 clears $30/hr',
    format: 'onsite',
    verify: 'official',
    requirements: "Bachelor's OR ~1 yr specialized experience for most GS-7/9 roles. US citizenship + background check. Set a Saved Search to get emailed when matching jobs open.",
    notes: 'USAJOBS is the ONLY legit federal application site. Open the link, then filter Grade = GS-7/GS-9. Boise typically has ~20+ federal reqs open at a time (VA is the biggest employer).',
    whereLabel: 'USAJOBS — Boise (live)',
    url: 'https://www.usajobs.gov/Search/Results?l=Boise%2C%20Idaho',
  },
  {
    category: 'Government',
    title: 'State of Idaho — HR / Financial Specialist, Compliance, Business Analyst, IT',
    pay: '$30–$40/hr ($62k–$83k/yr) at Specialist/Officer/Analyst level',
    format: 'hybrid',
    verify: 'official',
    requirements: 'Entry-to-mid generalist. Associate/bachelor or equivalent experience. Merit-system application, sometimes an online exam. Aim for "Specialist/Officer/Analyst" titles — clerk roles start ~$17–20/hr.',
    notes: 'CORRECTED LINK: Idaho moved off governmentjobs.com to this official site. Includes the PERSI pension. ~125 state jobs open in Boise at a time — sort by salary, descending.',
    whereLabel: 'statecareers.idaho.gov (live)',
    url: 'https://statecareers.idaho.gov/',
  },
  {
    category: 'Government',
    title: 'City of Meridian — Senior Admin / Permit Tech / Utility Operator / Code Enforcement',
    pay: '$30–$40/hr (senior/technician tier; entry clerk roles are lower)',
    format: 'onsite',
    verify: 'official',
    requirements: 'Entry-to-mid generalist. Senior admin, planning/permit technician, utility operator (cert or trainee track), code enforcement. Some need a cert or 1–2 yrs experience.',
    notes: 'Your home city (83642) — closest local-government employer. Smaller volume (~11 open at a time). Open the link and target senior/technician titles, not entry clerk.',
    whereLabel: 'City of Meridian Jobs (live)',
    url: 'https://apps.meridiancity.org/jobs/',
  },
  {
    category: 'Government',
    title: 'City of Boise — Wastewater Operator / Senior CSR / Trades / Admin Specialist',
    pay: '$30–$40/hr (with operator cert); trainee path available',
    format: 'onsite',
    verify: 'official',
    requirements: 'Generalist-friendly. Wastewater Operator-in-training (get Idaho Class I/OIT license within 6 mo), senior CSR, maintenance/trades, admin specialists. Background check + drug screen.',
    notes: 'Strong benefits: real pension, near-free healthcare, 401k match, tuition reimbursement. Wastewater Operator I/II are a reliable $30+ on-ramp and recur often.',
    whereLabel: 'City of Boise Careers (live)',
    url: 'https://www.governmentjobs.com/careers/boiseid',
  },
  {
    category: 'Government',
    title: 'Ada County — 911 Dispatcher / Detention Deputy / Appraiser / Accounting Specialist',
    pay: '$30+/hr after training/certification (pay ladders)',
    format: 'onsite',
    verify: 'official',
    requirements: 'Generalist routes: accounting/admin specialist, elections, appraiser trainee, 911 dispatcher (paid training), detention deputy (academy). Dispatch academies run on fixed cycles — check current open dates.',
    notes: '2,100+ employees, 20 departments. Public-safety support roles clear $30/hr after certification. Note dispatch hiring is cohort-based, so a posting may be between cycles.',
    whereLabel: 'Ada County Careers (live)',
    url: 'https://adacounty.id.gov/human-resources/county-careers/',
  },
  {
    category: 'Government',
    title: 'West Ada School District (Meridian) — IT Support, Skilled Trades, Teacher',
    pay: 'IT support ~$40k–$45k; teachers ~$48k–$70k+; skilled supervisors $30+/hr',
    format: 'onsite',
    verify: 'official',
    requirements: 'Non-cert $30 routes: IT support, skilled trades, maintenance/nutrition supervisors. Classroom roles need a teaching cert. (Aide/para roles start $16–$22/hr.)',
    notes: 'CORRECTED LINK: West Ada moved hiring to the Red Rover portal. This is the Meridian district — your local one. Good schedule + benefits.',
    whereLabel: 'West Ada Jobs — Red Rover (live)',
    url: 'https://jobs.redroverk12.com/org/wasd',
  },

  // ───────────────────────────── OFFICE / ADMIN ─────────────────────────────
  {
    category: 'Office / Admin',
    title: 'Project Coordinator',
    pay: '~$27–$42/hr; avg ~$69.5k/yr — reliably hits $30+',
    format: 'hybrid',
    verify: 'aggregator',
    requirements: '2–5 yrs coordinating projects, scheduling, budget/document tracking; MS Project / Smartsheet / Asana. CAPM/PMP helps. Construction/engineering/tech reach the top end.',
    notes: 'Strong $30+ office pick. Aggregator link = real listings but check each posting date. Employers hiring locally: ACCO, Lennar, State of Idaho, Lumin8.',
    whereLabel: 'ZipRecruiter (mixed currency)',
    url: 'https://www.ziprecruiter.com/Jobs/Project-Coordinator/-in-Boise,ID',
  },
  {
    category: 'Office / Admin',
    title: 'Customer Success Manager (Idaho-friendly remote)',
    pay: 'US remote avg ~$83k/yr; manager level easily $30+/hr',
    format: 'remote',
    verify: 'aggregator',
    requirements: '2–4+ yrs customer-facing / account management / SaaS support. Strong communication + CRM (Salesforce/HubSpot). Entry "CS Specialist" is the on-ramp; CSM clears $30/hr.',
    notes: 'Best path to $30+ while staying remote in Idaho. Target NATIONAL remote roles (Idaho in-state CS pay ranks low). Given your engineering + SaaS background, this is one of your strongest fits.',
    whereLabel: 'Indeed remote (mixed currency)',
    url: 'https://www.indeed.com/q-customer-success-manager-remote-jobs.html',
  },
  {
    category: 'Office / Admin',
    title: 'Operations / HR Coordinator → Generalist',
    pay: '~$26–$40/hr; coordinator sits near $30, Generalist clears it',
    format: 'hybrid',
    verify: 'aggregator',
    requirements: '2–5 yrs ops or HR support; process/vendor management, HRIS (Workday/ADP), reporting. Step up to "Generalist / Business Partner / Manager" titles to reliably exceed $30/hr. PHR/SHRM-CP helps for HR.',
    notes: 'Pays best at scaled employers — Micron, Clearwater Analytics, St. Luke’s. Aggregator link; verify each posting date.',
    whereLabel: 'LinkedIn (mixed currency)',
    url: 'https://www.linkedin.com/jobs/search/?keywords=operations%20coordinator&location=Boise%2C%20Idaho',
  },
  {
    category: 'Office / Admin',
    title: 'Executive Assistant / Office Manager / Bookkeeper (via staffing)',
    pay: '$25–$40/hr placements',
    format: 'hybrid',
    verify: 'official',
    requirements: 'Robert Half places EAs, office managers, bookkeepers & finance pros into contract, contract-to-hire, and direct-hire roles. Submit a resume and a recruiter matches you — fastest way to break $30 without a senior title.',
    notes: 'Robert Half is the dominant admin/finance staffing firm in Boise. Official recruiter portal (not a third-party board). Also try Express Employment, Aerotek/Actalent.',
    whereLabel: 'Robert Half Boise (official)',
    url: 'https://www.roberthalf.com/us/en/jobs/boise/all',
  },
  {
    category: 'Office / Admin',
    title: 'Apply direct to major Boise/Meridian employers',
    pay: 'Varies — large employers most reliably post $30+ admin/ops roles + benefits',
    format: 'hybrid',
    verify: 'official',
    requirements: 'Apply on company career sites (usually pays more + better benefits than staffing). Tailor your resume per posting; large employers screen via ATS keywords.',
    notes: 'Micron is in a massive AI-driven expansion (17,000+ new Idaho jobs planned) = heavy demand for admin/ops/coordinator support. Also: Albertsons HQ, St. Luke’s, Clearwater Analytics, HP, Simplot, Idaho Power.',
    whereLabel: 'Micron Careers (official)',
    url: 'https://careers.micron.com',
  },

  // ─────────────────────── TECH / VIRTUAL ASSISTANT (REMOTE) ───────────────────────
  {
    category: 'Tech / VA (Remote)',
    title: 'AI Data Labeling / Model Training — DataAnnotation',
    pay: '$20–$40/hr; coding $25–$45/hr; expert work up to $55+/hr',
    format: 'remote',
    verify: 'signup',
    requirements: 'Strong writing/reasoning; coding or domain expertise boosts pay & access. Unpaid screening assessment to qualify. No degree strictly required.',
    notes: 'LEGIT (operated by Surge AI). Always-open signup, not a dated posting. Caveat: task availability is feast-or-famine — best as supplemental income, not a sole job. 1099. Given your dev background you can target the higher-paid coding tasks.',
    whereLabel: 'DataAnnotation (apply anytime)',
    url: 'https://www.dataannotation.tech',
  },
  {
    category: 'Tech / VA (Remote)',
    title: 'AI Trainer / Expert — Mercor',
    pay: 'Avg ~$31/hr; specialized/expert tracks $40–$100+/hr',
    format: 'remote',
    verify: 'signup',
    requirements: 'Resume + AI video interview screening. Geared toward credentialed experts (degree / professional experience). Software-engineering specialty is in high demand.',
    notes: 'LEGIT — vets and matches experts to AI labs. Always-open application. Apply only via mercor.com. Your full-stack + MCP background fits the software-expert track (top of the pay range).',
    whereLabel: 'Mercor (apply anytime)',
    url: 'https://mercor.com',
  },
  {
    category: 'Tech / VA (Remote)',
    title: 'Virtual Executive Assistant — Boldly (W2 + benefits)',
    pay: '$27–$31/hr, W2 employee with PTO, benefits, tech stipend',
    format: 'remote',
    verify: 'signup',
    requirements: 'High bar: ~7–10+ yrs executive/admin assistant experience. Rigorous, selective vetting. US-based — Idaho eligible.',
    notes: 'LEGIT and one of the few W2 (not 1099) VA options. Always-open application. Apply directly; never pay to apply. (This one fits the "personal assistant" idea you mentioned.)',
    whereLabel: 'Boldly Careers (apply anytime)',
    url: 'https://boldly.com/careers',
  },
  {
    category: 'Tech / VA (Remote)',
    title: 'Remote Technical Support / Help Desk / IT Support',
    pay: '~$23/hr entry; CompTIA A+ roles avg ~$31/hr; dual-cert ~$34/hr',
    format: 'remote',
    verify: 'aggregator',
    requirements: 'Troubleshoot hardware/software/networks by phone/chat/email. Certs raise pay sharply — Google IT Support Certificate and/or CompTIA A+. (Your dev experience likely lets you skip entry tier.)',
    notes: 'LEGIT category. Aggregator link — check posting dates. Dell, HP, BCBS hire A+ holders. Google cert: grow.google/certificates/it-support',
    whereLabel: 'Indeed $30 remote (mixed currency)',
    url: 'https://www.indeed.com/q-tech-support-$30-l-remote-jobs.html',
  },
  {
    category: 'Tech / VA (Remote)',
    title: 'Online Tutoring (set-your-own-rate platforms)',
    pay: '$15–$80+/hr; Wyzant tutors set $30–$100+ (keep ~75%)',
    format: 'remote',
    verify: 'signup',
    requirements: 'Subject mastery. Wyzant/Preply need no formal credential. High-demand subjects (coding, math, test prep, science) pay most — you could tutor programming.',
    notes: 'Platforms are LEGIT and always-open. Avoid tutoring "jobs" on general boards (scam-prone) — sign up on the platform directly. Preply: Java ~$30, JavaScript ~$45/hr.',
    whereLabel: 'Wyzant (apply anytime)',
    url: 'https://www.wyzant.com/tutor',
  },

  // ─────────────────────── OTHER / GENERALIST PATHS ───────────────────────
  {
    category: 'Other / Generalist',
    title: 'Outside Sales / Account Rep (base + uncapped commission)',
    pay: '$70k–$120k OTE (~$34–$58/hr equivalent)',
    format: 'hybrid',
    verify: 'aggregator',
    requirements: 'Low formal barrier — motivation, communication, reliable vehicle. Packaging, business services, medical device, home services all hire generalists and train.',
    notes: 'Best income ceiling here for a motivated generalist. Early ramp may dip below $30 — target roles with a guaranteed draw/base. Aggregator link; verify each posting.',
    whereLabel: 'ZipRecruiter Sales (mixed currency)',
    url: 'https://www.ziprecruiter.com/Jobs/Sales/-in-Boise,ID',
  },
  {
    category: 'Other / Generalist',
    title: 'Warehouse / Logistics Supervisor or Lead',
    pay: '$30.00–$33.68/hr (lead/supervisor tier; night & 2nd shift pay more)',
    format: 'onsite',
    verify: 'aggregator',
    requirements: 'Supervisory/leadership experience in a warehouse setting. Any team-lead history qualifies. (Associate roles are $18–$20/hr.)',
    notes: 'Meridian/Boise have a large distribution presence (Amazon, retail DCs). Take an associate role and promote into lead if needed. Aggregator link; check dates.',
    whereLabel: 'Indeed Warehouse (mixed currency)',
    url: 'https://www.indeed.com/q-warehouse-jobs-l-boise,-id-jobs.html',
  },
  {
    category: 'Other / Generalist',
    title: 'Freelance Bookkeeper (remote, your own clients)',
    pay: '$20–$50/hr; $30+ achievable with a few clients + QuickBooks cert',
    format: 'remote',
    verify: 'signup',
    requirements: 'Low startup cost. No degree. Get QuickBooks Online Accountant (free) + optional Certified Bookkeeper cert. Build clients via referrals/freelance platforms.',
    notes: 'Scalable side-business. Start with Intuit/QuickBooks Live W-2 work to learn, then convert to higher-rate clients. You already run businesses, so the operator side is familiar.',
    whereLabel: 'Intuit Bookkeeping (apply anytime)',
    url: 'https://www.intuit.com/expert-careers/bookkeeping-jobs/',
  },
  {
    category: 'Other / Generalist',
    title: 'Skilled Trades Apprentice (Electrical / Plumbing / HVAC)',
    pay: 'Starts ~$17–$20/hr → ~$30/hr by year 3–4; journeyman median ~$30/hr',
    format: 'onsite',
    verify: 'official',
    requirements: 'No degree. Get hired by a contractor + enroll in apprenticeship (IEC Idaho or CWI). "Earn while you learn" — paid from day one with structured raises.',
    notes: 'Not instant $30 — a 2–4 yr ramp — but durable, high-ceiling, recession-resistant. Plumbing/electrical reach $30 fastest.',
    whereLabel: 'IEC Idaho Apprenticeship (official)',
    url: 'https://iecidaho.com/careers/',
  },
  {
    category: 'Other / Generalist',
    title: 'Local CDL-A Driver / High-end Delivery Driver',
    pay: '$29–$31.50/hr; some local delivery roles explicitly $30/hr + incentives',
    format: 'onsite',
    verify: 'aggregator',
    requirements: 'Some $30 delivery roles need only a regular license. CDL-A: company-paid training available (Sysco, Waste Connections) removes upfront cost. Local hauls keep you home nightly.',
    notes: 'Meridian-based hauls available (Ruan). Hiring: Sysco, PepsiCo, Waste Connections, AAA Cooper. Aggregator link; check dates.',
    whereLabel: 'ZipRecruiter CDL (mixed currency)',
    url: 'https://www.ziprecruiter.com/Jobs/Cdl-Truck-Driver/-in-Boise,ID',
  },

  // ─────────────────────── REFERENCE: AVOID SCAMS ───────────────────────
  {
    category: 'Avoid Scams',
    title: '⚠️ How to spot a job scam (read this first)',
    pay: 'Remote-job-scam losses hit $521M in 2026 (FTC)',
    format: 'remote',
    verify: 'official',
    requirements: 'RED FLAGS: pay for training/equipment/background checks; payment via crypto/gift cards/wire/Zelle; "deposit this check and forward money"; reshipping packages; hired in hours with no real interview; vague generic listings.',
    notes: 'VERIFY every employer: BBB, Glassdoor, and search "company name + scam". Legit employers NEVER ask you to pay or move money. Apply via official company sites only.',
    whereLabel: 'FTC Job Scams (official)',
    url: 'https://consumer.ftc.gov/articles/job-scams',
  },
];
