import Link from "next/link";
import { pageMetadata } from "@/lib/seo";
import { BRAND } from "@/config/brand";
import { VERTICALS } from "@/lib/verticals";
import { getAllSites } from "@/data/sites";
import { Section, Eyebrow, H2, Lead, Card, CTAButton } from "@/components/ui";

export const metadata = pageMetadata({
  title: "Templates & live demos — Pick a site built for your business",
  description:
    "Browse SEO-ready website templates for every kind of local business, and tour real live demo sites generated by LaunchLocal for businesses across the Treasure Valley.",
  path: "/templates",
});

export default function TemplatesPage() {
  const sites = getAllSites();

  return (
    <>
      <Section>
        <Eyebrow>Templates</Eyebrow>
        <H2>A site built for your kind of business</H2>
        <Lead>
          Every template is pre-tuned for how {BRAND.region} customers actually search and buy.
          Pick your business type to see what your site can do.
        </Lead>

        <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {VERTICALS.map((v) => (
            <Link
              key={v.slug}
              href={`/websites-for/${v.slug}`}
              className="card group flex flex-col transition hover:-translate-y-0.5 hover:shadow-lg"
            >
              <div className="text-4xl" aria-hidden>
                {v.emoji}
              </div>
              <h3 className="mt-4 text-lg font-bold text-ink">{v.name}</h3>
              <p className="mt-2 flex-1 text-sm text-ink-soft">{v.pain}</p>
              <span className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-brand-600">
                Websites for {v.plural}
                <span aria-hidden className="transition group-hover:translate-x-0.5">
                  →
                </span>
              </span>
            </Link>
          ))}
        </div>
      </Section>

      {sites.length > 0 && (
        <Section className="bg-brand-50">
          <div className="max-w-2xl">
            <Eyebrow>Live demos</Eyebrow>
            <H2>See real generated sites</H2>
            <Lead>
              These are full, live sites generated by {BRAND.name} — hero, services with prices,
              a working buy button, reviews, and service-area pages. Click through and imagine
              your business in the driver’s seat.
            </Lead>
          </div>

          <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {sites.map((site) => (
              <Link
                key={site.slug}
                href={`/sites/${site.slug}`}
                className="card group flex flex-col transition hover:-translate-y-0.5 hover:shadow-lg"
              >
                <div className="flex items-center justify-between">
                  <span className="text-3xl" aria-hidden>
                    {site.logoUrl ? "" : "🏢"}
                  </span>
                  <span className="rounded-full bg-brand-100 px-2.5 py-0.5 text-xs font-semibold uppercase tracking-wide text-brand-700">
                    {site.plan}
                  </span>
                </div>
                <h3 className="mt-4 text-lg font-bold text-ink">{site.businessName}</h3>
                <p className="mt-1 text-sm font-medium text-brand-600">{site.tagline}</p>
                <p className="mt-2 flex-1 text-sm text-ink-soft">
                  {site.primaryCity}
                  {site.citiesServed.length > 1
                    ? ` + ${site.citiesServed.length - 1} more cities`
                    : ""}
                </p>
                <span className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-brand-600">
                  View live demo
                  <span aria-hidden className="transition group-hover:translate-x-0.5">
                    →
                  </span>
                </span>
              </Link>
            ))}
          </div>
        </Section>
      )}

      <Section>
        <Card className="flex flex-col items-start gap-6 bg-brand-900 text-white md:flex-row md:items-center md:justify-between">
          <div>
            <h2 className="text-2xl font-extrabold tracking-tight sm:text-3xl">
              Don’t just look — launch yours
            </h2>
            <p className="mt-2 max-w-xl text-brand-100">
              Pick your template, add your info, and go live today with SEO, a buy button, and
              automation that runs for you.
            </p>
          </div>
          <div className="flex flex-wrap gap-3">
            <CTAButton href="/start">Start onboarding</CTAButton>
            <Link
              href="/how-it-works"
              className="btn-ghost border border-white/30 text-white hover:bg-white/10"
            >
              How it works
            </Link>
          </div>
        </Card>
      </Section>
    </>
  );
}
